# Generated by Django 4.2.7 on 2024-03-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_id_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='user',
            new_name='creator',
        ),
    ]
